services:
  db:
    image: postgres:16-alpine
    container_name: fymusic-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: fymusic
      POSTGRES_PASSWORD: fymusic
      POSTGRES_DB: fymusic
    ports:
      - "5435:5432"
    volumes:
      - fymusic-db-data:/var/lib/postgresql/data

volumes:
  fymusic-db-data: